### ISSUE TITLE
How can i install... ?

### ISSUE THREAD

**Issue by chagdo87** [Frogperson/Emoji-Roles#1]
Hey! Pretty stupid question i know but how can i install this to my discord bot (working with discord.js) please ?

**Comment by Frogperson** [comment]
Yeah sorry, I kind of forgot to add that part to the readme...

Just download the latest release: https://github.com/Frogperson/Emoji-Roles/releases
Make sure you have java installed on whatever you're running this on,
Then do `java -jar EmojiRoles-1.3.1.jar`

After you run it once it should generate the config file for you to put your token in, then just run it again.


Let me know if you need any more help!

**Comment by chagdo87** [comment]
Thanks ! I followed the steps, the bot is on my server but commands doesnt work and i get this error in my terminal https://hastebin.com/oduvayoyov.sql

**Comment by Frogperson** [comment]
Those first errors, the
```SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
```
is just because I don't have any of logging libraries, it shouldn't matter at all.

The second error:
```javax.security.auth.login.LoginException: The provided token is invalid!
        at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:276)
        at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:214)
        at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:161)
        at net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:608)
        at net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:647)
        at net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:676)
        at org.frogperson.emojiroles.EmojiRoles.main(EmojiRoles.java:59)
```
is just because there's no second bot token for one of the optional features of the bot, and again, shouldn't matter at all.

The commands likely aren't working for you because by default they only work if you have a role named `admins`, you can change the role name in the settings.conf file

**Comment by chagdo87** [comment]
Yep! Forgot to change it, thanks a lot! Works perfectly now!
